#!/usr/bin/perl

use strict;

my %indMat = ();
my @row = ();
my $sum = 0;

my $numSpeeches;
my $numNEs;

my $line = <STDIN>;
chomp($line);

if ($line =~ m/^speeches:(.*)$/ )
{
	print $line."\n";
	$numSpeeches = $1;
	
	$line = <STDIN>;
	chomp($line);
	
	print $line."\n";
	if ($line =~ m/^NEs:(.*)$/ )
	{
		$numNEs = $1;
	}
	else { die "Second line $line has incorrect format"; }
}
else { die "First line $line has incorrect format"; }

my @sum = ();

for (my $i = 0; $i < $numSpeeches; $i++)
{
	$sum[$i] = 0;
}

while ($line = <STDIN>)
{
	chomp($line);
	if ($line =~ m/^\(([0-9]+),([0-9]+)\)=([0-9]+)$/)
	{
		$sum[$1] += $3;
		$indMat{"$1,$2"} = $3;
	}
	else
	{
		die "Line doesn't match: $line";
	}
}

foreach my $key (keys %indMat)
{
	if ($key =~ m/^([0-9]+),([0-9]+)/)
	{
		print "($key)=".($indMat{$key} / $sum[$1])."\n";		
	}
	else { die "key doesn't match: $key"; }
}
