#!/usr/bin/perl

use strict;

my $neListFile = $ARGV[0];
my $inpFilesList = $ARGV[1];

open(NELIST, "<$neListFile") || die "Can't open $neListFile";
open(INPFILES, "<$inpFilesList") || die "Can't open $inpFilesList";

my %neTypeCounts = ();
my %NE = ();
my $neTyp = "";
my $ind = 0;
my %index = ();

while (my $line = <NELIST>)
{
	chomp($line);
	if ($line =~ m/^<(.*)>$/)
	{
	   $neTyp = $1;
	   $ind = 0;
	}
	else
	{
		#print "line: $line\n";
		if ($line =~ m/^([0-9]+) (.*)$/)
		{
		  $NE{"$neTyp,$2"} = $1;
		  
		  if ($1 != $ind) { die "$1 is not equal to ".$ind."!"; }
		  
		  #print "NE{$neTyp}{$1} = ".$NE{$neTyp}{$1}."\n";
		  $ind++;
		  $neTypeCounts{$neTyp} = $ind;
		}
		else
		{
			#die "Line doesn't match: $line";
		}
	}

}

close(NELIST);

my $neName;
my $neCount;

my $counter = 0;

while (my $line = <INPFILES>)
{
	chomp($line);
	my $mod = "";
	
	if ($line =~ m/^([0-9]+) (.*)/)
	{
		if ($1 != $counter) { die "$1 != ".$counter; }
		$line = "../data/".$2.".nerd";
	}
	
	open(FILE, "<$line") || die "Can't open file $line";
	#print "$line\n";
	while (my $radek = <FILE>)
	{
		chomp($radek);
	    #print "processing: $radek\n";
		if ($radek =~ m/^<(.*)>$/)
		{
			$mod = "";
			if ($1 ne "PERSONS" && $1 ne "LOCATIONS" && $1 ne "ORGANIZATIONS")
			{
				next;
			}
			
			$mod = $1;
		}
		elsif ($mod ne "")
		{
			if ($radek =~ m/^(.*) ([0-9]+)$/)
			{
			  $neName = $1;
			  $neCount = $2;
			  if (!(defined($NE{"$mod,$neName"})))
			  {
			  	die "Undefined named entity: $mod->$neName";
			  }
			  
			 
			  $index{"$mod,$counter,".$NE{"$mod,$neName"}} = $neCount;
			  #print "{$mod}[$counter][".$NE{$mod}{$neName}." - 1] = ".$index{$mod}[$counter][$NE{$mod}{$neName} - 1]."\n";
			}
			else
			{
				die "NE line doesn't match: $radek";
			}
			
		}
		
	}
	
	$counter++;
	close(FILE);
}

close(INPFILES);

foreach my $indType ("PERSONS", "ORGANIZATIONS", "LOCATIONS")
{
  open(INDEXOUT, ">$indType.ind");
  print INDEXOUT "speeches:".$counter."\n";
  print INDEXOUT "NEs:".$neTypeCounts{$indType}."\n";

  foreach my $key (sort keys %index)
  {
  	if ($key =~ m/^$indType,([0-9]+),([0-9]+)/)
  	{
  		print INDEXOUT "($1,$2)=".$index{$key}."\n";
  	}
  }

  close(INDEXOUT);  
}

