#!/usr/bin/perl

use strict;

my @indMat = ();
my @row = ();
my $sum = 0;

my $numSpeeches;
my $numNEs;

my %docsPerNE = ();

my $line = <STDIN>;
chomp($line);

if ($line =~ m/^speeches:(.*)$/ )
{
	print $line."\n";
	$numSpeeches = $1;
	
	$line = <STDIN>;
	chomp($line);
	
	print $line."\n";
	if ($line =~ m/^NEs:(.*)$/ )
	{
		$numNEs = $1;
	}
	else { die "Second line $line has incorrect format"; }
}
else { die "First line $line has incorrect format"; }

my $sum;

my @matrix = ();

my @row;

for (my $i = 0; $i < $numSpeeches; $i++)
{
	@row = ();
	$sum = 0;
	
	for (my $j = 0; $j < $numNEs; $j++)
	{
		$line = <STDIN>;
		chomp($line);
		if ($line eq "-----") { die "inconsistent data! Shouldn't be -----"; }
		
		if ($line > 0) { $docsPerNE{$j}++; }
		
		push(@row, $line);
		
	}
		
	$line = <STDIN>;
	chomp($line);
	
	if ($line ne "-----") { die "inconsistent data! Should be -----, but it's $line"; }
	
	push(@matrix, join(' ', @row));
}

my $logTerm;

for (my $i = 0; $i < $numSpeeches; $i++)
{
	@row = split(/ /, $matrix[$i]);
	$sum = 0;
	
	for (my $j = 0; $j < $numNEs; $j++)
	{
		if ($docsPerNE{$j} > 0)
		{
			if ($docsPerNE{$j} <= 3)
			{
				$logTerm = 1;
			}
			else
			{
				$logTerm = log($numSpeeches / $docsPerNE{$j});
			}
		}
		else
		{
			die "This is weird!\n";
			$logTerm = 1;
		}
		
		$row[$j] = $row[$j] * $logTerm;
		$sum += $row[$j];
	}
	
	for (my $j = 0; $j < $numNEs; $j++)
	{
		if ($sum > 0)
		{
			$row[$j] = $row[$j] / $sum;
		}
		else
		{
			$row[$j] = 0;
		}
		
		print $row[$j]."\n";
	}
	
	print "-----\n";
}

if (!eof(STDIN)) { die "stdin not closed!";}
